title: Stochastic programming and robust optimisation
author: Fabricio Oliveira
logo: _static/sidebar_logo.png
only_build_toc_files: true

# Code execution settings
execute:
  execute_notebooks: force  # See https://jupyterbook.org/content/execute.html

bibtex_bibfiles:
  - references.bib

# File parsing settings
parse:
  myst_enable_extensions:
    - amsmath       # For LaTeX math
    - colon_fence   # Allow use of ::: for admonitions, instead of just ```
    - substitution  # Define and use of markdown "variables"
    - linkify       # Auto-detect HTML-like links and convert them to hyperlinks.
    - dollarmath    # Allow $$ and $ syntax for math blocks

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex   ### DON'T CHANGE: jupyterbook-pdf.yml expects this to be book.tex, so if you want to change this change that as well.

# Information about where the book exists on the web
repository:
  url: https://github.com/gamma-opt/jb_course_template  # Online location of your book
  branch: main                                          # Which branch of the repository should be used when creating links (optional)

sphinx:
  extra_extensions:
    - sphinx_proof
    - sphinxcontrib.mermaid
  config:
    html_theme: quantecon_book_theme
    numfig_secnum_depth: 1  # https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-numfig_secnum_depth
    latex_domain_indices: false  # don't make proof index in PDF when using sphinx-proof
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js  # Enable MathJax 3
    mathjax3_config:
      loader:
        load: ["[tex]/textmacros"]  # For ~ to work as non-breaking space
      tex:
        packages:
          "[+]": ["textmacros"]     # For ~ to work as non-breaking space
        # If you add something, you should probably add to latex_elements below as well
        packages:
          "[+]": ["textmacros"]     # For ~ to work as non-breaking space
        # If you add something, you should probably add to latex_elements below as well
        macros:
          "reals": "\\mathbb{R}"
          "integers": "\\mathbb{Z}"
          "symm": "\\mathbb{S}"
          "rank": "\\mathop{\\bf rank}"
          "tr": "\\mathop{\\bf tr}"
          "dim": "\\mathop{\\bf dim}"
          "diag": "\\mathop{\\bf diag}"
          "conv": "\\mathop{\\bf conv}"
          "spans": "\\mathop{\\bf span}"
          "nulls": "\\mathop{\\bf null}"
          "clo": "\\mathop{\\bf clo}"
          "det": "\\mathop{\\bf det}"
          "proj": "\\mathop{\\bf proj}"
          "argmin": "\\mathop{\\rm argmin}"
          "argmax": "\\mathop{\\rm argmax}"
          "epi": "\\mathop{\\bf epi}"
          "dom": "\\mathop{\\bf dom}"
          "intr": "\\mathop{\\bf int}"
          "bou": "\\mathop{\\bf bou}"
          "mini": "\\mathop{\\text{min.~}}"
          "maxi": "\\mathop{\\text{max.~}}"
          "minf": "\\mathop{\\text{minimize~}}"
          "maxf": "\\mathop{\\text{maximize~}}"
          "st": "\\mathop{\\text{s.t.:~}}"
          "stf": "\\mathop{\\text{subject to:~}}"
          "nth": "^\\text{th}"
          "braces": ["\\left\\{ #1 \\right \\}", 1]
          "brackets": ["\\left[ #1 \\right]", 1]
          "floor": ["\\lfloor #1 \\rfloor", 1]
          "ceil": ["\\lceil #1 \\rceil", 1]
    latex_elements:
      # Gets copied into the tex file before the document start
      preamble: |
        \newcommand{\reals}{\mathbb{R}}
        \newcommand{\integers}{\mathbb{Z}}
        \newcommand{\symm}{\mathbb{S}}  % symmetric matrices
        \newcommand{\rank}{\mathop{\bf rank}}
        \newcommand{\tr}{\mathop{\bf tr}}
        \renewcommand{\dim}{\mathop{\bf dim}}
        \newcommand{\diag}{\mathop{\bf diag}}
        \newcommand{\conv}{\mathop{\bf conv}}
        \newcommand{\spans}{\mathop{\bf span}}
        \newcommand{\nulls}{\mathop{\bf null}}
        \newcommand{\clo}{\mathop{\bf clo}}
        \renewcommand{\det}{\mathop{\bf det}}
        \renewcommand{\proj}{\mathop{\bf proj}}
        \renewcommand{\argmin}{\mathop{\rm argmin}}
        \renewcommand{\argmax}{\mathop{\rm argmax}}
        \newcommand{\epi}{\mathop{\bf epi}} % epigraph
        \newcommand{\dom}{\mathop{\bf dom}} % domain
        \newcommand{\intr}{\mathop{\bf int}}
        \newcommand{\bou}{\mathop{\bf bou}}
        \newcommand{\mini}{\mathop{\text{min.~}}}
        \newcommand{\maxi}{\mathop{\text{max.~}}}
        \newcommand{\minf}{\mathop{\text{minimize~}}}
        \newcommand{\maxf}{\mathop{\text{maximize~}}}
        \newcommand{\st}{\mathop{\text{s.t.:~}}}
        \newcommand{\stf}{\mathop{\text{subject to:~}}}
        \newcommand{\nth}{^\text{th}}
        \newcommand{\braces}[1]{\left\{ #1 \right \}}
        \newcommand{\brackets}[1]{\left[ #1 \right]}
        \newcommand{\floor}[1]{\lfloor #1 \rfloor}
        \newcommand{\ceil}[1]{\lceil #1 \rceil}
